/**
 * TH1
 * TH1
 *
 * The version of the OpenAPI document: 1.28.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Report from './Report';
import TableStructure from './TableStructure';

/**
 * The TableStructureGenerationResponse model module.
 * @module model/TableStructureGenerationResponse
 * @version 1.28.0
 */
class TableStructureGenerationResponse {
    /**
     * Constructs a new <code>TableStructureGenerationResponse</code>.
     * @alias module:model/TableStructureGenerationResponse
     * @param tableStructure {module:model/TableStructure} 
     * @param reports {Array.<module:model/Report>} 
     */
    constructor(tableStructure, reports) { 
        
        TableStructureGenerationResponse.initialize(this, tableStructure, reports);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, tableStructure, reports) { 
        obj['tableStructure'] = tableStructure;
        obj['reports'] = reports;
    }

    /**
     * Constructs a <code>TableStructureGenerationResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TableStructureGenerationResponse} obj Optional instance to populate.
     * @return {module:model/TableStructureGenerationResponse} The populated <code>TableStructureGenerationResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TableStructureGenerationResponse();

            if (data.hasOwnProperty('tableStructure')) {
                obj['tableStructure'] = TableStructure.constructFromObject(data['tableStructure']);
            }
            if (data.hasOwnProperty('reports')) {
                obj['reports'] = ApiClient.convertToType(data['reports'], [Report]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>TableStructureGenerationResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>TableStructureGenerationResponse</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of TableStructureGenerationResponse.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // validate the optional field `tableStructure`
        if (data['tableStructure']) { // data not null
          TableStructure.validateJSON(data['tableStructure']);
        }
        if (data['reports']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['reports'])) {
                throw new Error("Expected the field `reports` to be an array in the JSON data but got " + data['reports']);
            }
            // validate the optional field `reports` (array)
            for (const item of data['reports']) {
                Report.validateJSON(item);
            };
        }

        return true;
    }


}

TableStructureGenerationResponse.RequiredProperties = ["tableStructure", "reports"];

/**
 * @member {module:model/TableStructure} tableStructure
 */
TableStructureGenerationResponse.prototype['tableStructure'] = undefined;

/**
 * @member {Array.<module:model/Report>} reports
 */
TableStructureGenerationResponse.prototype['reports'] = undefined;






export default TableStructureGenerationResponse;

