/**
 * TH1
 * TH1
 *
 * The version of the OpenAPI document: 1.28.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import AddHeaderNameStructure from './model/AddHeaderNameStructure';
import ColumnTypeMismatch from './model/ColumnTypeMismatch';
import ColumnTypeMismatchReport from './model/ColumnTypeMismatchReport';
import ConverterType from './model/ConverterType';
import EmptyColumnReport from './model/EmptyColumnReport';
import EmptyHeaderReport from './model/EmptyHeaderReport';
import EmptyRowReport from './model/EmptyRowReport';
import Feedback from './model/Feedback';
import FillEmptyColumnStructure from './model/FillEmptyColumnStructure';
import FillEmptyRowStructure from './model/FillEmptyRowStructure';
import GroupedHeaderReport from './model/GroupedHeaderReport';
import HeaderPlacementType from './model/HeaderPlacementType';
import MatchType from './model/MatchType';
import MatcherType from './model/MatcherType';
import MergeColumnsStructure from './model/MergeColumnsStructure';
import MergeableColumnsReport from './model/MergeableColumnsReport';
import MissingEntryReport from './model/MissingEntryReport';
import PivotMatrixStructure from './model/PivotMatrixStructure';
import Position from './model/Position';
import RemoveColumnByIndexStructure from './model/RemoveColumnByIndexStructure';
import RemoveColumnsSettings from './model/RemoveColumnsSettings';
import RemoveFooterSettings from './model/RemoveFooterSettings';
import RemoveFooterStructure from './model/RemoveFooterStructure';
import RemoveGroupedHeaderStructure from './model/RemoveGroupedHeaderStructure';
import RemoveHeaderSettings from './model/RemoveHeaderSettings';
import RemoveHeaderStructure from './model/RemoveHeaderStructure';
import RemoveInvalidRowsSettings from './model/RemoveInvalidRowsSettings';
import RemoveInvalidRowsStructure from './model/RemoveInvalidRowsStructure';
import RemoveKeywordStructure from './model/RemoveKeywordStructure';
import RemoveKeywordsSettings from './model/RemoveKeywordsSettings';
import RemoveKeywordsStructure from './model/RemoveKeywordsStructure';
import RemoveLeadingColumnSettings from './model/RemoveLeadingColumnSettings';
import RemoveLeadingColumnStructure from './model/RemoveLeadingColumnStructure';
import RemoveLeadingColumnsSettings from './model/RemoveLeadingColumnsSettings';
import RemoveRowByIndexStructure from './model/RemoveRowByIndexStructure';
import RemoveTrailingColumnSettings from './model/RemoveTrailingColumnSettings';
import RemoveTrailingColumnStructure from './model/RemoveTrailingColumnStructure';
import ReplaceEntriesStructure from './model/ReplaceEntriesStructure';
import Report from './model/Report';
import ReportType from './model/ReportType';
import SameAsHeaderReport from './model/SameAsHeaderReport';
import SplitCellStructure from './model/SplitCellStructure';
import SplitRowReport from './model/SplitRowReport';
import Structure from './model/Structure';
import StructureSummary from './model/StructureSummary';
import SumReport from './model/SumReport';
import TableStructure from './model/TableStructure';
import TableStructureGenerationResponse from './model/TableStructureGenerationResponse';
import TableStructureGenerationSettings from './model/TableStructureGenerationSettings';
import TableStructureSummary from './model/TableStructureSummary';
import TransposeMatrixReport from './model/TransposeMatrixReport';
import TransposeMatrixStructure from './model/TransposeMatrixStructure';
import DefaultApi from './api/DefaultApi';


/**
* TH1.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var Th1 = require('index'); // See note below*.
* var xxxSvc = new Th1.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new Th1.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new Th1.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new Th1.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.28.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The AddHeaderNameStructure model constructor.
     * @property {module:model/AddHeaderNameStructure}
     */
    AddHeaderNameStructure,

    /**
     * The ColumnTypeMismatch model constructor.
     * @property {module:model/ColumnTypeMismatch}
     */
    ColumnTypeMismatch,

    /**
     * The ColumnTypeMismatchReport model constructor.
     * @property {module:model/ColumnTypeMismatchReport}
     */
    ColumnTypeMismatchReport,

    /**
     * The ConverterType model constructor.
     * @property {module:model/ConverterType}
     */
    ConverterType,

    /**
     * The EmptyColumnReport model constructor.
     * @property {module:model/EmptyColumnReport}
     */
    EmptyColumnReport,

    /**
     * The EmptyHeaderReport model constructor.
     * @property {module:model/EmptyHeaderReport}
     */
    EmptyHeaderReport,

    /**
     * The EmptyRowReport model constructor.
     * @property {module:model/EmptyRowReport}
     */
    EmptyRowReport,

    /**
     * The Feedback model constructor.
     * @property {module:model/Feedback}
     */
    Feedback,

    /**
     * The FillEmptyColumnStructure model constructor.
     * @property {module:model/FillEmptyColumnStructure}
     */
    FillEmptyColumnStructure,

    /**
     * The FillEmptyRowStructure model constructor.
     * @property {module:model/FillEmptyRowStructure}
     */
    FillEmptyRowStructure,

    /**
     * The GroupedHeaderReport model constructor.
     * @property {module:model/GroupedHeaderReport}
     */
    GroupedHeaderReport,

    /**
     * The HeaderPlacementType model constructor.
     * @property {module:model/HeaderPlacementType}
     */
    HeaderPlacementType,

    /**
     * The MatchType model constructor.
     * @property {module:model/MatchType}
     */
    MatchType,

    /**
     * The MatcherType model constructor.
     * @property {module:model/MatcherType}
     */
    MatcherType,

    /**
     * The MergeColumnsStructure model constructor.
     * @property {module:model/MergeColumnsStructure}
     */
    MergeColumnsStructure,

    /**
     * The MergeableColumnsReport model constructor.
     * @property {module:model/MergeableColumnsReport}
     */
    MergeableColumnsReport,

    /**
     * The MissingEntryReport model constructor.
     * @property {module:model/MissingEntryReport}
     */
    MissingEntryReport,

    /**
     * The PivotMatrixStructure model constructor.
     * @property {module:model/PivotMatrixStructure}
     */
    PivotMatrixStructure,

    /**
     * The Position model constructor.
     * @property {module:model/Position}
     */
    Position,

    /**
     * The RemoveColumnByIndexStructure model constructor.
     * @property {module:model/RemoveColumnByIndexStructure}
     */
    RemoveColumnByIndexStructure,

    /**
     * The RemoveColumnsSettings model constructor.
     * @property {module:model/RemoveColumnsSettings}
     */
    RemoveColumnsSettings,

    /**
     * The RemoveFooterSettings model constructor.
     * @property {module:model/RemoveFooterSettings}
     */
    RemoveFooterSettings,

    /**
     * The RemoveFooterStructure model constructor.
     * @property {module:model/RemoveFooterStructure}
     */
    RemoveFooterStructure,

    /**
     * The RemoveGroupedHeaderStructure model constructor.
     * @property {module:model/RemoveGroupedHeaderStructure}
     */
    RemoveGroupedHeaderStructure,

    /**
     * The RemoveHeaderSettings model constructor.
     * @property {module:model/RemoveHeaderSettings}
     */
    RemoveHeaderSettings,

    /**
     * The RemoveHeaderStructure model constructor.
     * @property {module:model/RemoveHeaderStructure}
     */
    RemoveHeaderStructure,

    /**
     * The RemoveInvalidRowsSettings model constructor.
     * @property {module:model/RemoveInvalidRowsSettings}
     */
    RemoveInvalidRowsSettings,

    /**
     * The RemoveInvalidRowsStructure model constructor.
     * @property {module:model/RemoveInvalidRowsStructure}
     */
    RemoveInvalidRowsStructure,

    /**
     * The RemoveKeywordStructure model constructor.
     * @property {module:model/RemoveKeywordStructure}
     */
    RemoveKeywordStructure,

    /**
     * The RemoveKeywordsSettings model constructor.
     * @property {module:model/RemoveKeywordsSettings}
     */
    RemoveKeywordsSettings,

    /**
     * The RemoveKeywordsStructure model constructor.
     * @property {module:model/RemoveKeywordsStructure}
     */
    RemoveKeywordsStructure,

    /**
     * The RemoveLeadingColumnSettings model constructor.
     * @property {module:model/RemoveLeadingColumnSettings}
     */
    RemoveLeadingColumnSettings,

    /**
     * The RemoveLeadingColumnStructure model constructor.
     * @property {module:model/RemoveLeadingColumnStructure}
     */
    RemoveLeadingColumnStructure,

    /**
     * The RemoveLeadingColumnsSettings model constructor.
     * @property {module:model/RemoveLeadingColumnsSettings}
     */
    RemoveLeadingColumnsSettings,

    /**
     * The RemoveRowByIndexStructure model constructor.
     * @property {module:model/RemoveRowByIndexStructure}
     */
    RemoveRowByIndexStructure,

    /**
     * The RemoveTrailingColumnSettings model constructor.
     * @property {module:model/RemoveTrailingColumnSettings}
     */
    RemoveTrailingColumnSettings,

    /**
     * The RemoveTrailingColumnStructure model constructor.
     * @property {module:model/RemoveTrailingColumnStructure}
     */
    RemoveTrailingColumnStructure,

    /**
     * The ReplaceEntriesStructure model constructor.
     * @property {module:model/ReplaceEntriesStructure}
     */
    ReplaceEntriesStructure,

    /**
     * The Report model constructor.
     * @property {module:model/Report}
     */
    Report,

    /**
     * The ReportType model constructor.
     * @property {module:model/ReportType}
     */
    ReportType,

    /**
     * The SameAsHeaderReport model constructor.
     * @property {module:model/SameAsHeaderReport}
     */
    SameAsHeaderReport,

    /**
     * The SplitCellStructure model constructor.
     * @property {module:model/SplitCellStructure}
     */
    SplitCellStructure,

    /**
     * The SplitRowReport model constructor.
     * @property {module:model/SplitRowReport}
     */
    SplitRowReport,

    /**
     * The Structure model constructor.
     * @property {module:model/Structure}
     */
    Structure,

    /**
     * The StructureSummary model constructor.
     * @property {module:model/StructureSummary}
     */
    StructureSummary,

    /**
     * The SumReport model constructor.
     * @property {module:model/SumReport}
     */
    SumReport,

    /**
     * The TableStructure model constructor.
     * @property {module:model/TableStructure}
     */
    TableStructure,

    /**
     * The TableStructureGenerationResponse model constructor.
     * @property {module:model/TableStructureGenerationResponse}
     */
    TableStructureGenerationResponse,

    /**
     * The TableStructureGenerationSettings model constructor.
     * @property {module:model/TableStructureGenerationSettings}
     */
    TableStructureGenerationSettings,

    /**
     * The TableStructureSummary model constructor.
     * @property {module:model/TableStructureSummary}
     */
    TableStructureSummary,

    /**
     * The TransposeMatrixReport model constructor.
     * @property {module:model/TransposeMatrixReport}
     */
    TransposeMatrixReport,

    /**
     * The TransposeMatrixStructure model constructor.
     * @property {module:model/TransposeMatrixStructure}
     */
    TransposeMatrixStructure,

    /**
    * The DefaultApi service constructor.
    * @property {module:api/DefaultApi}
    */
    DefaultApi
};
