/**
 * Th1nk
 * Th1nk
 *
 * The version of the OpenAPI document: 1.28.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class ConverterType.
* @enum {}
* @readonly
*/
export default class ConverterType {
    
        /**
         * value: "REMOVE_GROUPED_HEADER"
         * @const
         */
        "REMOVE_GROUPED_HEADER" = "REMOVE_GROUPED_HEADER";

    
        /**
         * value: "FILL_EMPTY_ROW"
         * @const
         */
        "FILL_EMPTY_ROW" = "FILL_EMPTY_ROW";

    
        /**
         * value: "FILL_EMPTY_COLUMN"
         * @const
         */
        "FILL_EMPTY_COLUMN" = "FILL_EMPTY_COLUMN";

    
        /**
         * value: "REMOVE_COLUMN_BY_INDEX"
         * @const
         */
        "REMOVE_COLUMN_BY_INDEX" = "REMOVE_COLUMN_BY_INDEX";

    
        /**
         * value: "REMOVE_ROW_BY_INDEX"
         * @const
         */
        "REMOVE_ROW_BY_INDEX" = "REMOVE_ROW_BY_INDEX";

    
        /**
         * value: "ADD_HEADER_NAME"
         * @const
         */
        "ADD_HEADER_NAME" = "ADD_HEADER_NAME";

    
        /**
         * value: "REMOVE_FOOTER"
         * @const
         */
        "REMOVE_FOOTER" = "REMOVE_FOOTER";

    
        /**
         * value: "REMOVE_HEADER"
         * @const
         */
        "REMOVE_HEADER" = "REMOVE_HEADER";

    
        /**
         * value: "REPLACE_ENTRIES"
         * @const
         */
        "REPLACE_ENTRIES" = "REPLACE_ENTRIES";

    
        /**
         * value: "SPLIT_CELL"
         * @const
         */
        "SPLIT_CELL" = "SPLIT_CELL";

    
        /**
         * value: "REMOVE_INVALID_ROWS"
         * @const
         */
        "REMOVE_INVALID_ROWS" = "REMOVE_INVALID_ROWS";

    
        /**
         * value: "REMOVE_TRAILING_COLUMN"
         * @const
         */
        "REMOVE_TRAILING_COLUMN" = "REMOVE_TRAILING_COLUMN";

    
        /**
         * value: "REMOVE_LEADING_COLUMN"
         * @const
         */
        "REMOVE_LEADING_COLUMN" = "REMOVE_LEADING_COLUMN";

    
        /**
         * value: "MERGE_COLUMNS"
         * @const
         */
        "MERGE_COLUMNS" = "MERGE_COLUMNS";

    
        /**
         * value: "TRANSPOSE_MATRIX"
         * @const
         */
        "TRANSPOSE_MATRIX" = "TRANSPOSE_MATRIX";

    
        /**
         * value: "PIVOT_MATRIX"
         * @const
         */
        "PIVOT_MATRIX" = "PIVOT_MATRIX";

    
        /**
         * value: "REMOVE_KEYWORD"
         * @const
         */
        "REMOVE_KEYWORD" = "REMOVE_KEYWORD";

    

    /**
    * Returns a <code>ConverterType</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/ConverterType} The enum <code>ConverterType</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

