/**
 * Th1nk
 * Th1nk
 *
 * The version of the OpenAPI document: 1.28.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Feedback model module.
 * @module model/Feedback
 * @version 1.28.0
 */
class Feedback {
    /**
     * Constructs a new <code>Feedback</code>.
     * This represents a feedback message.
     * @alias module:model/Feedback
     * @param content {String} The content of the feedback message. This can be an arbitrary string. 
     */
    constructor(content) { 
        
        Feedback.initialize(this, content);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, content) { 
        obj['content'] = content;
    }

    /**
     * Constructs a <code>Feedback</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Feedback} obj Optional instance to populate.
     * @return {module:model/Feedback} The populated <code>Feedback</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Feedback();

            if (data.hasOwnProperty('content')) {
                obj['content'] = ApiClient.convertToType(data['content'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Feedback</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Feedback</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of Feedback.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['content'] && !(typeof data['content'] === 'string' || data['content'] instanceof String)) {
            throw new Error("Expected the field `content` to be a primitive type in the JSON string but got " + data['content']);
        }

        return true;
    }


}

Feedback.RequiredProperties = ["content"];

/**
 * The content of the feedback message. This can be an arbitrary string. 
 * @member {String} content
 */
Feedback.prototype['content'] = undefined;






export default Feedback;

