/**
 * Th1nk
 * Th1nk
 *
 * The version of the OpenAPI document: 1.28.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class MatcherType.
* @enum {}
* @readonly
*/
export default class MatcherType {
    
        /**
         * value: "CONTAINS"
         * @const
         */
        "CONTAINS" = "CONTAINS";

    
        /**
         * value: "EQUALS"
         * @const
         */
        "EQUALS" = "EQUALS";

    

    /**
    * Returns a <code>MatcherType</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/MatcherType} The enum <code>MatcherType</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

