/**
 * Th1nk
 * Th1nk
 *
 * The version of the OpenAPI document: 1.28.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ReportType from './ReportType';

/**
 * The MergeableColumnsReport model module.
 * @module model/MergeableColumnsReport
 * @version 1.28.0
 */
class MergeableColumnsReport {
    /**
     * Constructs a new <code>MergeableColumnsReport</code>.
     * This report indicates that the specified columns are mergeable. This is report is generated if a tuple of columns have entries where other columns in the tuple are empty.  The reportType MUST be MERGEABLE_COLUMNS. 
     * @alias module:model/MergeableColumnsReport
     * @param reportType {module:model/ReportType} 
     */
    constructor(reportType) { 
        
        MergeableColumnsReport.initialize(this, reportType);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, reportType) { 
        obj['reportType'] = reportType;
    }

    /**
     * Constructs a <code>MergeableColumnsReport</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MergeableColumnsReport} obj Optional instance to populate.
     * @return {module:model/MergeableColumnsReport} The populated <code>MergeableColumnsReport</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MergeableColumnsReport();

            if (data.hasOwnProperty('reportType')) {
                obj['reportType'] = ReportType.constructFromObject(data['reportType']);
            }
            if (data.hasOwnProperty('mergeables')) {
                obj['mergeables'] = ApiClient.convertToType(data['mergeables'], ['Number']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>MergeableColumnsReport</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>MergeableColumnsReport</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of MergeableColumnsReport.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is an array
        if (!Array.isArray(data['mergeables'])) {
            throw new Error("Expected the field `mergeables` to be an array in the JSON data but got " + data['mergeables']);
        }

        return true;
    }


}

MergeableColumnsReport.RequiredProperties = ["reportType"];

/**
 * @member {module:model/ReportType} reportType
 */
MergeableColumnsReport.prototype['reportType'] = undefined;

/**
 * @member {Array.<Number>} mergeables
 */
MergeableColumnsReport.prototype['mergeables'] = undefined;






export default MergeableColumnsReport;

