/**
 * Th1nk
 * Th1nk
 *
 * The version of the OpenAPI document: 1.28.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ConverterType from './ConverterType';

/**
 * The RemoveHeaderStructure model module.
 * @module model/RemoveHeaderStructure
 * @version 1.28.0
 */
class RemoveHeaderStructure {
    /**
     * Constructs a new <code>RemoveHeaderStructure</code>.
     * This converter removes the header from the table. The header is defined as the first rows of the table which only contain a maximum of threshold invalid values. The invalid values are empty cells by default but can be extended using the blockList properties.  The converterType MUST be REMOVE_HEADER. 
     * @alias module:model/RemoveHeaderStructure
     * @param converterType {module:model/ConverterType} 
     */
    constructor(converterType) { 
        
        RemoveHeaderStructure.initialize(this, converterType);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, converterType) { 
        obj['converterType'] = converterType;
    }

    /**
     * Constructs a <code>RemoveHeaderStructure</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RemoveHeaderStructure} obj Optional instance to populate.
     * @return {module:model/RemoveHeaderStructure} The populated <code>RemoveHeaderStructure</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RemoveHeaderStructure();

            if (data.hasOwnProperty('converterType')) {
                obj['converterType'] = ConverterType.constructFromObject(data['converterType']);
            }
            if (data.hasOwnProperty('threshold')) {
                obj['threshold'] = ApiClient.convertToType(data['threshold'], 'Number');
            }
            if (data.hasOwnProperty('blockList')) {
                obj['blockList'] = ApiClient.convertToType(data['blockList'], ['String']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>RemoveHeaderStructure</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>RemoveHeaderStructure</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of RemoveHeaderStructure.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is an array
        if (!Array.isArray(data['blockList'])) {
            throw new Error("Expected the field `blockList` to be an array in the JSON data but got " + data['blockList']);
        }

        return true;
    }


}

RemoveHeaderStructure.RequiredProperties = ["converterType"];

/**
 * @member {module:model/ConverterType} converterType
 */
RemoveHeaderStructure.prototype['converterType'] = undefined;

/**
 * The maximum number of invalid values in a row to be considered a header row.
 * @member {Number} threshold
 */
RemoveHeaderStructure.prototype['threshold'] = undefined;

/**
 * The list of values to be considered invalid.
 * @member {Array.<String>} blockList
 */
RemoveHeaderStructure.prototype['blockList'] = undefined;






export default RemoveHeaderStructure;

