/**
 * Th1nk
 * Th1nk
 *
 * The version of the OpenAPI document: 1.28.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ConverterType from './ConverterType';

/**
 * The RemoveColumnByIndexStructure model module.
 * @module model/RemoveColumnByIndexStructure
 * @version 1.28.0
 */
class RemoveColumnByIndexStructure {
    /**
     * Constructs a new <code>RemoveColumnByIndexStructure</code>.
     * This converter removes the specified columns from the table. If the specified column index is out of bounds, an error will be thrown.  The converterType MUST be REMOVE_COLUMN_BY_INDEX. 
     * @alias module:model/RemoveColumnByIndexStructure
     * @param converterType {module:model/ConverterType} 
     * @param columnIndex {Array.<Number>} The indices of the columns to remove
     */
    constructor(converterType, columnIndex) { 
        
        RemoveColumnByIndexStructure.initialize(this, converterType, columnIndex);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, converterType, columnIndex) { 
        obj['converterType'] = converterType;
        obj['columnIndex'] = columnIndex;
    }

    /**
     * Constructs a <code>RemoveColumnByIndexStructure</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RemoveColumnByIndexStructure} obj Optional instance to populate.
     * @return {module:model/RemoveColumnByIndexStructure} The populated <code>RemoveColumnByIndexStructure</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RemoveColumnByIndexStructure();

            if (data.hasOwnProperty('converterType')) {
                obj['converterType'] = ConverterType.constructFromObject(data['converterType']);
            }
            if (data.hasOwnProperty('columnIndex')) {
                obj['columnIndex'] = ApiClient.convertToType(data['columnIndex'], ['Number']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>RemoveColumnByIndexStructure</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>RemoveColumnByIndexStructure</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of RemoveColumnByIndexStructure.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is an array
        if (!Array.isArray(data['columnIndex'])) {
            throw new Error("Expected the field `columnIndex` to be an array in the JSON data but got " + data['columnIndex']);
        }

        return true;
    }


}

RemoveColumnByIndexStructure.RequiredProperties = ["converterType", "columnIndex"];

/**
 * @member {module:model/ConverterType} converterType
 */
RemoveColumnByIndexStructure.prototype['converterType'] = undefined;

/**
 * The indices of the columns to remove
 * @member {Array.<Number>} columnIndex
 */
RemoveColumnByIndexStructure.prototype['columnIndex'] = undefined;






export default RemoveColumnByIndexStructure;

