/**
 * Th1nk
 * Th1nk
 *
 * The version of the OpenAPI document: 1.28.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The RemoveLeadingColumnSettings model module.
 * @module model/RemoveLeadingColumnSettings
 * @version 1.28.0
 */
class RemoveLeadingColumnSettings {
    /**
     * Constructs a new <code>RemoveLeadingColumnSettings</code>.
     * @alias module:model/RemoveLeadingColumnSettings
     * @param enabled {Boolean} 
     * @param blockList {Array.<String>} 
     */
    constructor(enabled, blockList) { 
        
        RemoveLeadingColumnSettings.initialize(this, enabled, blockList);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, enabled, blockList) { 
        obj['enabled'] = enabled || true;
        obj['blockList'] = blockList;
    }

    /**
     * Constructs a <code>RemoveLeadingColumnSettings</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RemoveLeadingColumnSettings} obj Optional instance to populate.
     * @return {module:model/RemoveLeadingColumnSettings} The populated <code>RemoveLeadingColumnSettings</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RemoveLeadingColumnSettings();

            if (data.hasOwnProperty('enabled')) {
                obj['enabled'] = ApiClient.convertToType(data['enabled'], 'Boolean');
            }
            if (data.hasOwnProperty('blockList')) {
                obj['blockList'] = ApiClient.convertToType(data['blockList'], ['String']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>RemoveLeadingColumnSettings</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>RemoveLeadingColumnSettings</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of RemoveLeadingColumnSettings.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is an array
        if (!Array.isArray(data['blockList'])) {
            throw new Error("Expected the field `blockList` to be an array in the JSON data but got " + data['blockList']);
        }

        return true;
    }


}

RemoveLeadingColumnSettings.RequiredProperties = ["enabled", "blockList"];

/**
 * @member {Boolean} enabled
 * @default true
 */
RemoveLeadingColumnSettings.prototype['enabled'] = true;

/**
 * @member {Array.<String>} blockList
 */
RemoveLeadingColumnSettings.prototype['blockList'] = undefined;






export default RemoveLeadingColumnSettings;

