/**
 * Th1nk
 * Th1nk
 *
 * The version of the OpenAPI document: 1.28.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class ReportType.
* @enum {}
* @readonly
*/
export default class ReportType {
    
        /**
         * value: "COLUMN_TYPE_MISMATCH"
         * @const
         */
        "COLUMN_TYPE_MISMATCH" = "COLUMN_TYPE_MISMATCH";

    
        /**
         * value: "GROUPED_HEADER"
         * @const
         */
        "GROUPED_HEADER" = "GROUPED_HEADER";

    
        /**
         * value: "EMPTY_HEADER"
         * @const
         */
        "EMPTY_HEADER" = "EMPTY_HEADER";

    
        /**
         * value: "EMPTY_ROW"
         * @const
         */
        "EMPTY_ROW" = "EMPTY_ROW";

    
        /**
         * value: "EMPTY_COLUMN"
         * @const
         */
        "EMPTY_COLUMN" = "EMPTY_COLUMN";

    
        /**
         * value: "SAME_AS_HEADER"
         * @const
         */
        "SAME_AS_HEADER" = "SAME_AS_HEADER";

    
        /**
         * value: "MISSING_ENTRY"
         * @const
         */
        "MISSING_ENTRY" = "MISSING_ENTRY";

    
        /**
         * value: "MERGEABLE_COLUMNS"
         * @const
         */
        "MERGEABLE_COLUMNS" = "MERGEABLE_COLUMNS";

    
        /**
         * value: "SPLIT_ROW"
         * @const
         */
        "SPLIT_ROW" = "SPLIT_ROW";

    
        /**
         * value: "SUM"
         * @const
         */
        "SUM" = "SUM";

    
        /**
         * value: "TRANSPOSE_MATRIX"
         * @const
         */
        "TRANSPOSE_MATRIX" = "TRANSPOSE_MATRIX";

    

    /**
    * Returns a <code>ReportType</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/ReportType} The enum <code>ReportType</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

