/**
 * Th1nk
 * Th1nk
 *
 * The version of the OpenAPI document: 1.28.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import StructureSummary from './StructureSummary';

/**
 * The TableStructureSummary model module.
 * @module model/TableStructureSummary
 * @version 1.28.0
 */
class TableStructureSummary {
    /**
     * Constructs a new <code>TableStructureSummary</code>.
     * This is a summary of a table structure. It contains am ID, name, and an array of structure summaries. However, it does not contain the actual structure with its fields. 
     * @alias module:model/TableStructureSummary
     * @param id {Number} The ID of the table structure.
     * @param name {String} The name of the table structure. This is an arbitrary string. 
     * @param structures {Array.<module:model/StructureSummary>} The list of structures in the table structure as summaries.
     */
    constructor(id, name, structures) { 
        
        TableStructureSummary.initialize(this, id, name, structures);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, name, structures) { 
        obj['id'] = id;
        obj['name'] = name;
        obj['structures'] = structures;
    }

    /**
     * Constructs a <code>TableStructureSummary</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TableStructureSummary} obj Optional instance to populate.
     * @return {module:model/TableStructureSummary} The populated <code>TableStructureSummary</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TableStructureSummary();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('structures')) {
                obj['structures'] = ApiClient.convertToType(data['structures'], [StructureSummary]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>TableStructureSummary</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>TableStructureSummary</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of TableStructureSummary.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        if (data['structures']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['structures'])) {
                throw new Error("Expected the field `structures` to be an array in the JSON data but got " + data['structures']);
            }
            // validate the optional field `structures` (array)
            for (const item of data['structures']) {
                StructureSummary.validateJSON(item);
            };
        }

        return true;
    }


}

TableStructureSummary.RequiredProperties = ["id", "name", "structures"];

/**
 * The ID of the table structure.
 * @member {Number} id
 */
TableStructureSummary.prototype['id'] = undefined;

/**
 * The name of the table structure. This is an arbitrary string. 
 * @member {String} name
 */
TableStructureSummary.prototype['name'] = undefined;

/**
 * The list of structures in the table structure as summaries.
 * @member {Array.<module:model/StructureSummary>} structures
 */
TableStructureSummary.prototype['structures'] = undefined;






export default TableStructureSummary;

