/**
 * Th1nk
 * Th1nk
 *
 * The version of the OpenAPI document: 1.28.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import RemoveFooterSettings from './RemoveFooterSettings';
import RemoveHeaderSettings from './RemoveHeaderSettings';
import RemoveInvalidRowsSettings from './RemoveInvalidRowsSettings';
import RemoveKeywordsSettings from './RemoveKeywordsSettings';
import RemoveLeadingColumnSettings from './RemoveLeadingColumnSettings';
import RemoveTrailingColumnSettings from './RemoveTrailingColumnSettings';

/**
 * The TableStructureGenerationSettings model module.
 * @module model/TableStructureGenerationSettings
 * @version 1.28.0
 */
class TableStructureGenerationSettings {
    /**
     * Constructs a new <code>TableStructureGenerationSettings</code>.
     * @alias module:model/TableStructureGenerationSettings
     */
    constructor() { 
        
        TableStructureGenerationSettings.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
        obj['maxIterations'] = 5;
    }

    /**
     * Constructs a <code>TableStructureGenerationSettings</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TableStructureGenerationSettings} obj Optional instance to populate.
     * @return {module:model/TableStructureGenerationSettings} The populated <code>TableStructureGenerationSettings</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TableStructureGenerationSettings();

            if (data.hasOwnProperty('removeHeader')) {
                obj['removeHeader'] = RemoveHeaderSettings.constructFromObject(data['removeHeader']);
            }
            if (data.hasOwnProperty('removeFooter')) {
                obj['removeFooter'] = RemoveFooterSettings.constructFromObject(data['removeFooter']);
            }
            if (data.hasOwnProperty('removeTrailingColumn')) {
                obj['removeTrailingColumn'] = RemoveTrailingColumnSettings.constructFromObject(data['removeTrailingColumn']);
            }
            if (data.hasOwnProperty('removeLeadingColumn')) {
                obj['removeLeadingColumn'] = RemoveLeadingColumnSettings.constructFromObject(data['removeLeadingColumn']);
            }
            if (data.hasOwnProperty('removeInvalidRows')) {
                obj['removeInvalidRows'] = RemoveInvalidRowsSettings.constructFromObject(data['removeInvalidRows']);
            }
            if (data.hasOwnProperty('removeKeywords')) {
                obj['removeKeywords'] = RemoveKeywordsSettings.constructFromObject(data['removeKeywords']);
            }
            if (data.hasOwnProperty('maxIterations')) {
                obj['maxIterations'] = ApiClient.convertToType(data['maxIterations'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>TableStructureGenerationSettings</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>TableStructureGenerationSettings</code>.
     */
    static validateJSON(data) {
        // validate the optional field `removeHeader`
        if (data['removeHeader']) { // data not null
          RemoveHeaderSettings.validateJSON(data['removeHeader']);
        }
        // validate the optional field `removeFooter`
        if (data['removeFooter']) { // data not null
          RemoveFooterSettings.validateJSON(data['removeFooter']);
        }
        // validate the optional field `removeTrailingColumn`
        if (data['removeTrailingColumn']) { // data not null
          RemoveTrailingColumnSettings.validateJSON(data['removeTrailingColumn']);
        }
        // validate the optional field `removeLeadingColumn`
        if (data['removeLeadingColumn']) { // data not null
          RemoveLeadingColumnSettings.validateJSON(data['removeLeadingColumn']);
        }
        // validate the optional field `removeInvalidRows`
        if (data['removeInvalidRows']) { // data not null
          RemoveInvalidRowsSettings.validateJSON(data['removeInvalidRows']);
        }
        // validate the optional field `removeKeywords`
        if (data['removeKeywords']) { // data not null
          RemoveKeywordsSettings.validateJSON(data['removeKeywords']);
        }

        return true;
    }


}



/**
 * @member {module:model/RemoveHeaderSettings} removeHeader
 */
TableStructureGenerationSettings.prototype['removeHeader'] = undefined;

/**
 * @member {module:model/RemoveFooterSettings} removeFooter
 */
TableStructureGenerationSettings.prototype['removeFooter'] = undefined;

/**
 * @member {module:model/RemoveTrailingColumnSettings} removeTrailingColumn
 */
TableStructureGenerationSettings.prototype['removeTrailingColumn'] = undefined;

/**
 * @member {module:model/RemoveLeadingColumnSettings} removeLeadingColumn
 */
TableStructureGenerationSettings.prototype['removeLeadingColumn'] = undefined;

/**
 * @member {module:model/RemoveInvalidRowsSettings} removeInvalidRows
 */
TableStructureGenerationSettings.prototype['removeInvalidRows'] = undefined;

/**
 * @member {module:model/RemoveKeywordsSettings} removeKeywords
 */
TableStructureGenerationSettings.prototype['removeKeywords'] = undefined;

/**
 * @member {Number} maxIterations
 * @default 5
 */
TableStructureGenerationSettings.prototype['maxIterations'] = 5;






export default TableStructureGenerationSettings;

