/**
 * TH1
 * TH1
 *
 * The version of the OpenAPI document: 1.28.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ColumnTypeMismatch model module.
 * @module model/ColumnTypeMismatch
 * @version 1.28.0
 */
class ColumnTypeMismatch {
    /**
     * Constructs a new <code>ColumnTypeMismatch</code>.
     * This is a type mismatch report for a specific column in a table structure. 
     * @alias module:model/ColumnTypeMismatch
     * @param columnIndex {Array.<Number>} 
     */
    constructor(columnIndex) { 
        
        ColumnTypeMismatch.initialize(this, columnIndex);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, columnIndex) { 
        obj['columnIndex'] = columnIndex;
    }

    /**
     * Constructs a <code>ColumnTypeMismatch</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ColumnTypeMismatch} obj Optional instance to populate.
     * @return {module:model/ColumnTypeMismatch} The populated <code>ColumnTypeMismatch</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ColumnTypeMismatch();

            if (data.hasOwnProperty('columnIndex')) {
                obj['columnIndex'] = ApiClient.convertToType(data['columnIndex'], ['Number']);
            }
            if (data.hasOwnProperty('replacementSearch')) {
                obj['replacementSearch'] = ApiClient.convertToType(data['replacementSearch'], 'String');
            }
            if (data.hasOwnProperty('replacementValue')) {
                obj['replacementValue'] = ApiClient.convertToType(data['replacementValue'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ColumnTypeMismatch</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ColumnTypeMismatch</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ColumnTypeMismatch.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is an array
        if (!Array.isArray(data['columnIndex'])) {
            throw new Error("Expected the field `columnIndex` to be an array in the JSON data but got " + data['columnIndex']);
        }
        // ensure the json data is a string
        if (data['replacementSearch'] && !(typeof data['replacementSearch'] === 'string' || data['replacementSearch'] instanceof String)) {
            throw new Error("Expected the field `replacementSearch` to be a primitive type in the JSON string but got " + data['replacementSearch']);
        }
        // ensure the json data is a string
        if (data['replacementValue'] && !(typeof data['replacementValue'] === 'string' || data['replacementValue'] instanceof String)) {
            throw new Error("Expected the field `replacementValue` to be a primitive type in the JSON string but got " + data['replacementValue']);
        }

        return true;
    }


}

ColumnTypeMismatch.RequiredProperties = ["columnIndex"];

/**
 * @member {Array.<Number>} columnIndex
 */
ColumnTypeMismatch.prototype['columnIndex'] = undefined;

/**
 * If the mismatch can be resolved by replacing a value, this field contains the search string.
 * @member {String} replacementSearch
 */
ColumnTypeMismatch.prototype['replacementSearch'] = undefined;

/**
 * If the mismatch can be resolved by replacing a value, this field contains the replacement value.
 * @member {String} replacementValue
 */
ColumnTypeMismatch.prototype['replacementValue'] = undefined;






export default ColumnTypeMismatch;

