/**
 * TH1
 * TH1
 *
 * The version of the OpenAPI document: 1.28.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ConverterType from './ConverterType';

/**
 * The FillEmptyRowStructure model module.
 * @module model/FillEmptyRowStructure
 * @version 1.28.0
 */
class FillEmptyRowStructure {
    /**
     * Constructs a new <code>FillEmptyRowStructure</code>.
     * This converter fills empty cells in the specified rows. It iterates through each specified row and fills empty cells with the value from the last non-empty cell. If there are no non-empty cells in the row an error will be thrown. This converter expects a non-empty cell at the beginning of each specified row.  The converterType MUST be FILL_EMPTY_ROW. 
     * @alias module:model/FillEmptyRowStructure
     * @param converterType {module:model/ConverterType} 
     * @param rowIndex {Array.<Number>} The indices of the rows to fill
     */
    constructor(converterType, rowIndex) { 
        
        FillEmptyRowStructure.initialize(this, converterType, rowIndex);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, converterType, rowIndex) { 
        obj['converterType'] = converterType;
        obj['rowIndex'] = rowIndex;
    }

    /**
     * Constructs a <code>FillEmptyRowStructure</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/FillEmptyRowStructure} obj Optional instance to populate.
     * @return {module:model/FillEmptyRowStructure} The populated <code>FillEmptyRowStructure</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new FillEmptyRowStructure();

            if (data.hasOwnProperty('converterType')) {
                obj['converterType'] = ConverterType.constructFromObject(data['converterType']);
            }
            if (data.hasOwnProperty('rowIndex')) {
                obj['rowIndex'] = ApiClient.convertToType(data['rowIndex'], ['Number']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>FillEmptyRowStructure</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>FillEmptyRowStructure</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of FillEmptyRowStructure.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is an array
        if (!Array.isArray(data['rowIndex'])) {
            throw new Error("Expected the field `rowIndex` to be an array in the JSON data but got " + data['rowIndex']);
        }

        return true;
    }


}

FillEmptyRowStructure.RequiredProperties = ["converterType", "rowIndex"];

/**
 * @member {module:model/ConverterType} converterType
 */
FillEmptyRowStructure.prototype['converterType'] = undefined;

/**
 * The indices of the rows to fill
 * @member {Array.<Number>} rowIndex
 */
FillEmptyRowStructure.prototype['rowIndex'] = undefined;






export default FillEmptyRowStructure;

