/**
 * TH1
 * TH1
 *
 * The version of the OpenAPI document: 1.28.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class HeaderPlacementType.
* @enum {}
* @readonly
*/
export default class HeaderPlacementType {
    
        /**
         * value: "INSERT_AT_TOP"
         * @const
         */
        "INSERT_AT_TOP" = "INSERT_AT_TOP";

    
        /**
         * value: "REPLACE_FIRST_ROW"
         * @const
         */
        "REPLACE_FIRST_ROW" = "REPLACE_FIRST_ROW";

    

    /**
    * Returns a <code>HeaderPlacementType</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/HeaderPlacementType} The enum <code>HeaderPlacementType</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

