/**
 * TH1
 * TH1
 *
 * The version of the OpenAPI document: 1.28.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The RemoveKeywordsSettings model module.
 * @module model/RemoveKeywordsSettings
 * @version 1.28.0
 */
class RemoveKeywordsSettings {
    /**
     * Constructs a new <code>RemoveKeywordsSettings</code>.
     * @alias module:model/RemoveKeywordsSettings
     * @param enabled {Boolean} 
     * @param removeRows {Boolean} Whether to remove rows that contain a matching keyword.
     * @param removeColumns {Boolean} Whether to remove columns that contain a matching keyword.
     * @param ignoreCase {Boolean} 
     * @param matchType {module:model/RemoveKeywordsSettings.MatchTypeEnum} 
     */
    constructor(enabled, removeRows, removeColumns, ignoreCase, matchType) { 
        
        RemoveKeywordsSettings.initialize(this, enabled, removeRows, removeColumns, ignoreCase, matchType);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, enabled, removeRows, removeColumns, ignoreCase, matchType) { 
        obj['enabled'] = enabled || true;
        obj['removeRows'] = removeRows || true;
        obj['removeColumns'] = removeColumns || true;
        obj['ignoreCase'] = ignoreCase || true;
        obj['matchType'] = matchType || 'EQUALS';
    }

    /**
     * Constructs a <code>RemoveKeywordsSettings</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RemoveKeywordsSettings} obj Optional instance to populate.
     * @return {module:model/RemoveKeywordsSettings} The populated <code>RemoveKeywordsSettings</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RemoveKeywordsSettings();

            if (data.hasOwnProperty('enabled')) {
                obj['enabled'] = ApiClient.convertToType(data['enabled'], 'Boolean');
            }
            if (data.hasOwnProperty('keywords')) {
                obj['keywords'] = ApiClient.convertToType(data['keywords'], ['String']);
            }
            if (data.hasOwnProperty('removeRows')) {
                obj['removeRows'] = ApiClient.convertToType(data['removeRows'], 'Boolean');
            }
            if (data.hasOwnProperty('removeColumns')) {
                obj['removeColumns'] = ApiClient.convertToType(data['removeColumns'], 'Boolean');
            }
            if (data.hasOwnProperty('ignoreCase')) {
                obj['ignoreCase'] = ApiClient.convertToType(data['ignoreCase'], 'Boolean');
            }
            if (data.hasOwnProperty('matchType')) {
                obj['matchType'] = ApiClient.convertToType(data['matchType'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>RemoveKeywordsSettings</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>RemoveKeywordsSettings</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of RemoveKeywordsSettings.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is an array
        if (!Array.isArray(data['keywords'])) {
            throw new Error("Expected the field `keywords` to be an array in the JSON data but got " + data['keywords']);
        }
        // ensure the json data is a string
        if (data['matchType'] && !(typeof data['matchType'] === 'string' || data['matchType'] instanceof String)) {
            throw new Error("Expected the field `matchType` to be a primitive type in the JSON string but got " + data['matchType']);
        }

        return true;
    }


}

RemoveKeywordsSettings.RequiredProperties = ["enabled", "removeRows", "removeColumns", "ignoreCase", "matchType"];

/**
 * @member {Boolean} enabled
 * @default true
 */
RemoveKeywordsSettings.prototype['enabled'] = true;

/**
 * A list of keywords to match against.  If a cell contains any of these keywords, the corresponding row or column will be removed. 
 * @member {Array.<String>} keywords
 */
RemoveKeywordsSettings.prototype['keywords'] = undefined;

/**
 * Whether to remove rows that contain a matching keyword.
 * @member {Boolean} removeRows
 * @default true
 */
RemoveKeywordsSettings.prototype['removeRows'] = true;

/**
 * Whether to remove columns that contain a matching keyword.
 * @member {Boolean} removeColumns
 * @default true
 */
RemoveKeywordsSettings.prototype['removeColumns'] = true;

/**
 * @member {Boolean} ignoreCase
 * @default true
 */
RemoveKeywordsSettings.prototype['ignoreCase'] = true;

/**
 * @member {module:model/RemoveKeywordsSettings.MatchTypeEnum} matchType
 * @default 'EQUALS'
 */
RemoveKeywordsSettings.prototype['matchType'] = 'EQUALS';





/**
 * Allowed values for the <code>matchType</code> property.
 * @enum {String}
 * @readonly
 */
RemoveKeywordsSettings['MatchTypeEnum'] = {

    /**
     * value: "CONTAINS"
     * @const
     */
    "CONTAINS": "CONTAINS",

    /**
     * value: "EQUALS"
     * @const
     */
    "EQUALS": "EQUALS"
};



export default RemoveKeywordsSettings;

