/**
 * TH1
 * TH1
 *
 * The version of the OpenAPI document: 1.28.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AddHeaderNameStructure from './AddHeaderNameStructure';
import ConverterType from './ConverterType';
import FillEmptyColumnStructure from './FillEmptyColumnStructure';
import FillEmptyRowStructure from './FillEmptyRowStructure';
import HeaderPlacementType from './HeaderPlacementType';
import MatchType from './MatchType';
import MergeColumnsStructure from './MergeColumnsStructure';
import PivotMatrixStructure from './PivotMatrixStructure';
import RemoveColumnByIndexStructure from './RemoveColumnByIndexStructure';
import RemoveFooterStructure from './RemoveFooterStructure';
import RemoveGroupedHeaderStructure from './RemoveGroupedHeaderStructure';
import RemoveHeaderStructure from './RemoveHeaderStructure';
import RemoveInvalidRowsStructure from './RemoveInvalidRowsStructure';
import RemoveKeywordsStructure from './RemoveKeywordsStructure';
import RemoveLeadingColumnStructure from './RemoveLeadingColumnStructure';
import RemoveRowByIndexStructure from './RemoveRowByIndexStructure';
import RemoveTrailingColumnStructure from './RemoveTrailingColumnStructure';
import ReplaceEntriesStructure from './ReplaceEntriesStructure';
import SplitCellStructure from './SplitCellStructure';
import TransposeMatrixStructure from './TransposeMatrixStructure';

/**
 * The Structure model module.
 * @module model/Structure
 * @version 1.28.0
 */
class Structure {
    /**
     * Constructs a new <code>Structure</code>.
     * This is the base for all converter structures. The converterType is used as a discriminator to determine the specific structure. 
     * @alias module:model/Structure
     * @param {(module:model/AddHeaderNameStructure|module:model/FillEmptyColumnStructure|module:model/FillEmptyRowStructure|module:model/MergeColumnsStructure|module:model/PivotMatrixStructure|module:model/RemoveColumnByIndexStructure|module:model/RemoveFooterStructure|module:model/RemoveGroupedHeaderStructure|module:model/RemoveHeaderStructure|module:model/RemoveInvalidRowsStructure|module:model/RemoveKeywordsStructure|module:model/RemoveLeadingColumnStructure|module:model/RemoveRowByIndexStructure|module:model/RemoveTrailingColumnStructure|module:model/ReplaceEntriesStructure|module:model/SplitCellStructure|module:model/TransposeMatrixStructure)} instance The actual instance to initialize Structure.
     */
    constructor(instance = null) {
        if (instance === null) {
            this.actualInstance = null;
            return;
        }
        var match = 0;
        var errorMessages = [];
        var discriminatorInstance = null;
        // This is the base for all converter structures. The converterType is used as a discriminator to determine the specific structure. 
        try {
            if (typeof instance === "AddHeaderNameStructure") {
                this.actualInstance = instance;
            } else {
                // plain JS object
                // validate the object
                AddHeaderNameStructure.validateJSON(instance); // throw an exception if no match
                // create AddHeaderNameStructure from JS object
                this.actualInstance = AddHeaderNameStructure.constructFromObject(instance);
                if (instance.converterType == "ADD_HEADER_NAME")
                    discriminatorInstance = this.actualInstance;
            }
            match++;
        } catch(err) {
            // json data failed to deserialize into AddHeaderNameStructure
            errorMessages.push("Failed to construct AddHeaderNameStructure: " + err)
        }

        // This is the base for all converter structures. The converterType is used as a discriminator to determine the specific structure. 
        try {
            if (typeof instance === "FillEmptyColumnStructure") {
                this.actualInstance = instance;
            } else {
                // plain JS object
                // validate the object
                FillEmptyColumnStructure.validateJSON(instance); // throw an exception if no match
                // create FillEmptyColumnStructure from JS object
                this.actualInstance = FillEmptyColumnStructure.constructFromObject(instance);
                if (instance.converterType == "FILL_EMPTY_COLUMN")
                    discriminatorInstance = this.actualInstance;
            }
            match++;
        } catch(err) {
            // json data failed to deserialize into FillEmptyColumnStructure
            errorMessages.push("Failed to construct FillEmptyColumnStructure: " + err)
        }

        // This is the base for all converter structures. The converterType is used as a discriminator to determine the specific structure. 
        try {
            if (typeof instance === "FillEmptyRowStructure") {
                this.actualInstance = instance;
            } else {
                // plain JS object
                // validate the object
                FillEmptyRowStructure.validateJSON(instance); // throw an exception if no match
                // create FillEmptyRowStructure from JS object
                this.actualInstance = FillEmptyRowStructure.constructFromObject(instance);
                if (instance.converterType == "FILL_EMPTY_ROW")
                    discriminatorInstance = this.actualInstance;
            }
            match++;
        } catch(err) {
            // json data failed to deserialize into FillEmptyRowStructure
            errorMessages.push("Failed to construct FillEmptyRowStructure: " + err)
        }

        // This is the base for all converter structures. The converterType is used as a discriminator to determine the specific structure. 
        try {
            if (typeof instance === "MergeColumnsStructure") {
                this.actualInstance = instance;
            } else {
                // plain JS object
                // validate the object
                MergeColumnsStructure.validateJSON(instance); // throw an exception if no match
                // create MergeColumnsStructure from JS object
                this.actualInstance = MergeColumnsStructure.constructFromObject(instance);
                if (instance.converterType == "MERGE_COLUMNS")
                    discriminatorInstance = this.actualInstance;
            }
            match++;
        } catch(err) {
            // json data failed to deserialize into MergeColumnsStructure
            errorMessages.push("Failed to construct MergeColumnsStructure: " + err)
        }

        // This is the base for all converter structures. The converterType is used as a discriminator to determine the specific structure. 
        try {
            if (typeof instance === "PivotMatrixStructure") {
                this.actualInstance = instance;
            } else {
                // plain JS object
                // validate the object
                PivotMatrixStructure.validateJSON(instance); // throw an exception if no match
                // create PivotMatrixStructure from JS object
                this.actualInstance = PivotMatrixStructure.constructFromObject(instance);
                if (instance.converterType == "PIVOT_MATRIX")
                    discriminatorInstance = this.actualInstance;
            }
            match++;
        } catch(err) {
            // json data failed to deserialize into PivotMatrixStructure
            errorMessages.push("Failed to construct PivotMatrixStructure: " + err)
        }

        // This is the base for all converter structures. The converterType is used as a discriminator to determine the specific structure. 
        try {
            if (typeof instance === "RemoveColumnByIndexStructure") {
                this.actualInstance = instance;
            } else {
                // plain JS object
                // validate the object
                RemoveColumnByIndexStructure.validateJSON(instance); // throw an exception if no match
                // create RemoveColumnByIndexStructure from JS object
                this.actualInstance = RemoveColumnByIndexStructure.constructFromObject(instance);
                if (instance.converterType == "REMOVE_COLUMN_BY_INDEX")
                    discriminatorInstance = this.actualInstance;
            }
            match++;
        } catch(err) {
            // json data failed to deserialize into RemoveColumnByIndexStructure
            errorMessages.push("Failed to construct RemoveColumnByIndexStructure: " + err)
        }

        // This is the base for all converter structures. The converterType is used as a discriminator to determine the specific structure. 
        try {
            if (typeof instance === "RemoveFooterStructure") {
                this.actualInstance = instance;
            } else {
                // plain JS object
                // validate the object
                RemoveFooterStructure.validateJSON(instance); // throw an exception if no match
                // create RemoveFooterStructure from JS object
                this.actualInstance = RemoveFooterStructure.constructFromObject(instance);
                if (instance.converterType == "REMOVE_FOOTER")
                    discriminatorInstance = this.actualInstance;
            }
            match++;
        } catch(err) {
            // json data failed to deserialize into RemoveFooterStructure
            errorMessages.push("Failed to construct RemoveFooterStructure: " + err)
        }

        // This is the base for all converter structures. The converterType is used as a discriminator to determine the specific structure. 
        try {
            if (typeof instance === "RemoveGroupedHeaderStructure") {
                this.actualInstance = instance;
            } else {
                // plain JS object
                // validate the object
                RemoveGroupedHeaderStructure.validateJSON(instance); // throw an exception if no match
                // create RemoveGroupedHeaderStructure from JS object
                this.actualInstance = RemoveGroupedHeaderStructure.constructFromObject(instance);
                if (instance.converterType == "REMOVE_GROUPED_HEADER")
                    discriminatorInstance = this.actualInstance;
            }
            match++;
        } catch(err) {
            // json data failed to deserialize into RemoveGroupedHeaderStructure
            errorMessages.push("Failed to construct RemoveGroupedHeaderStructure: " + err)
        }

        // This is the base for all converter structures. The converterType is used as a discriminator to determine the specific structure. 
        try {
            if (typeof instance === "RemoveHeaderStructure") {
                this.actualInstance = instance;
            } else {
                // plain JS object
                // validate the object
                RemoveHeaderStructure.validateJSON(instance); // throw an exception if no match
                // create RemoveHeaderStructure from JS object
                this.actualInstance = RemoveHeaderStructure.constructFromObject(instance);
                if (instance.converterType == "REMOVE_HEADER")
                    discriminatorInstance = this.actualInstance;
            }
            match++;
        } catch(err) {
            // json data failed to deserialize into RemoveHeaderStructure
            errorMessages.push("Failed to construct RemoveHeaderStructure: " + err)
        }

        // This is the base for all converter structures. The converterType is used as a discriminator to determine the specific structure. 
        try {
            if (typeof instance === "RemoveInvalidRowsStructure") {
                this.actualInstance = instance;
            } else {
                // plain JS object
                // validate the object
                RemoveInvalidRowsStructure.validateJSON(instance); // throw an exception if no match
                // create RemoveInvalidRowsStructure from JS object
                this.actualInstance = RemoveInvalidRowsStructure.constructFromObject(instance);
                if (instance.converterType == "REMOVE_INVALID_ROWS")
                    discriminatorInstance = this.actualInstance;
            }
            match++;
        } catch(err) {
            // json data failed to deserialize into RemoveInvalidRowsStructure
            errorMessages.push("Failed to construct RemoveInvalidRowsStructure: " + err)
        }

        // This is the base for all converter structures. The converterType is used as a discriminator to determine the specific structure. 
        try {
            if (typeof instance === "RemoveKeywordsStructure") {
                this.actualInstance = instance;
            } else {
                // plain JS object
                // validate the object
                RemoveKeywordsStructure.validateJSON(instance); // throw an exception if no match
                // create RemoveKeywordsStructure from JS object
                this.actualInstance = RemoveKeywordsStructure.constructFromObject(instance);
                if (instance.converterType == "REMOVE_KEYWORD")
                    discriminatorInstance = this.actualInstance;
            }
            match++;
        } catch(err) {
            // json data failed to deserialize into RemoveKeywordsStructure
            errorMessages.push("Failed to construct RemoveKeywordsStructure: " + err)
        }

        // This is the base for all converter structures. The converterType is used as a discriminator to determine the specific structure. 
        try {
            if (typeof instance === "RemoveLeadingColumnStructure") {
                this.actualInstance = instance;
            } else {
                // plain JS object
                // validate the object
                RemoveLeadingColumnStructure.validateJSON(instance); // throw an exception if no match
                // create RemoveLeadingColumnStructure from JS object
                this.actualInstance = RemoveLeadingColumnStructure.constructFromObject(instance);
                if (instance.converterType == "REMOVE_LEADING_COLUMN")
                    discriminatorInstance = this.actualInstance;
            }
            match++;
        } catch(err) {
            // json data failed to deserialize into RemoveLeadingColumnStructure
            errorMessages.push("Failed to construct RemoveLeadingColumnStructure: " + err)
        }

        // This is the base for all converter structures. The converterType is used as a discriminator to determine the specific structure. 
        try {
            if (typeof instance === "RemoveRowByIndexStructure") {
                this.actualInstance = instance;
            } else {
                // plain JS object
                // validate the object
                RemoveRowByIndexStructure.validateJSON(instance); // throw an exception if no match
                // create RemoveRowByIndexStructure from JS object
                this.actualInstance = RemoveRowByIndexStructure.constructFromObject(instance);
                if (instance.converterType == "REMOVE_ROW_BY_INDEX")
                    discriminatorInstance = this.actualInstance;
            }
            match++;
        } catch(err) {
            // json data failed to deserialize into RemoveRowByIndexStructure
            errorMessages.push("Failed to construct RemoveRowByIndexStructure: " + err)
        }

        // This is the base for all converter structures. The converterType is used as a discriminator to determine the specific structure. 
        try {
            if (typeof instance === "RemoveTrailingColumnStructure") {
                this.actualInstance = instance;
            } else {
                // plain JS object
                // validate the object
                RemoveTrailingColumnStructure.validateJSON(instance); // throw an exception if no match
                // create RemoveTrailingColumnStructure from JS object
                this.actualInstance = RemoveTrailingColumnStructure.constructFromObject(instance);
                if (instance.converterType == "REMOVE_TRAILING_COLUMN")
                    discriminatorInstance = this.actualInstance;
            }
            match++;
        } catch(err) {
            // json data failed to deserialize into RemoveTrailingColumnStructure
            errorMessages.push("Failed to construct RemoveTrailingColumnStructure: " + err)
        }

        // This is the base for all converter structures. The converterType is used as a discriminator to determine the specific structure. 
        try {
            if (typeof instance === "ReplaceEntriesStructure") {
                this.actualInstance = instance;
            } else {
                // plain JS object
                // validate the object
                ReplaceEntriesStructure.validateJSON(instance); // throw an exception if no match
                // create ReplaceEntriesStructure from JS object
                this.actualInstance = ReplaceEntriesStructure.constructFromObject(instance);
                if (instance.converterType == "REPLACE_ENTRIES")
                    discriminatorInstance = this.actualInstance;
            }
            match++;
        } catch(err) {
            // json data failed to deserialize into ReplaceEntriesStructure
            errorMessages.push("Failed to construct ReplaceEntriesStructure: " + err)
        }

        // This is the base for all converter structures. The converterType is used as a discriminator to determine the specific structure. 
        try {
            if (typeof instance === "SplitCellStructure") {
                this.actualInstance = instance;
            } else {
                // plain JS object
                // validate the object
                SplitCellStructure.validateJSON(instance); // throw an exception if no match
                // create SplitCellStructure from JS object
                this.actualInstance = SplitCellStructure.constructFromObject(instance);
                if (instance.converterType == "SPLIT_CELL")
                    discriminatorInstance = this.actualInstance;
            }
            match++;
        } catch(err) {
            // json data failed to deserialize into SplitCellStructure
            errorMessages.push("Failed to construct SplitCellStructure: " + err)
        }

        // This is the base for all converter structures. The converterType is used as a discriminator to determine the specific structure. 
        try {
            if (typeof instance === "TransposeMatrixStructure") {
                this.actualInstance = instance;
            } else {
                // plain JS object
                // validate the object
                TransposeMatrixStructure.validateJSON(instance); // throw an exception if no match
                // create TransposeMatrixStructure from JS object
                this.actualInstance = TransposeMatrixStructure.constructFromObject(instance);
                if (instance.converterType == "TRANSPOSE_MATRIX")
                    discriminatorInstance = this.actualInstance;
            }
            match++;
        } catch(err) {
            // json data failed to deserialize into TransposeMatrixStructure
            errorMessages.push("Failed to construct TransposeMatrixStructure: " + err)
        }

        if (discriminatorInstance) {
            this.actualInstance = discriminatorInstance;
        } else if (match > 1) {
            throw new Error("Multiple matches found constructing `Structure` with oneOf schemas AddHeaderNameStructure, FillEmptyColumnStructure, FillEmptyRowStructure, MergeColumnsStructure, PivotMatrixStructure, RemoveColumnByIndexStructure, RemoveFooterStructure, RemoveGroupedHeaderStructure, RemoveHeaderStructure, RemoveInvalidRowsStructure, RemoveKeywordsStructure, RemoveLeadingColumnStructure, RemoveRowByIndexStructure, RemoveTrailingColumnStructure, ReplaceEntriesStructure, SplitCellStructure, TransposeMatrixStructure. Input: " + JSON.stringify(instance));
        } else if (match === 0) {
            this.actualInstance = null; // clear the actual instance in case there are multiple matches
            throw new Error("No match found constructing `Structure` with oneOf schemas AddHeaderNameStructure, FillEmptyColumnStructure, FillEmptyRowStructure, MergeColumnsStructure, PivotMatrixStructure, RemoveColumnByIndexStructure, RemoveFooterStructure, RemoveGroupedHeaderStructure, RemoveHeaderStructure, RemoveInvalidRowsStructure, RemoveKeywordsStructure, RemoveLeadingColumnStructure, RemoveRowByIndexStructure, RemoveTrailingColumnStructure, ReplaceEntriesStructure, SplitCellStructure, TransposeMatrixStructure. Details: " +
                            errorMessages.join(", "));
        } else { // only 1 match
            // the input is valid
        }
    }

    /**
     * Constructs a <code>Structure</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Structure} obj Optional instance to populate.
     * @return {module:model/Structure} The populated <code>Structure</code> instance.
     */
    static constructFromObject(data, obj) {
        return new Structure(data);
    }

    /**
     * Gets the actual instance, which can be <code>AddHeaderNameStructure</code>, <code>FillEmptyColumnStructure</code>, <code>FillEmptyRowStructure</code>, <code>MergeColumnsStructure</code>, <code>PivotMatrixStructure</code>, <code>RemoveColumnByIndexStructure</code>, <code>RemoveFooterStructure</code>, <code>RemoveGroupedHeaderStructure</code>, <code>RemoveHeaderStructure</code>, <code>RemoveInvalidRowsStructure</code>, <code>RemoveKeywordsStructure</code>, <code>RemoveLeadingColumnStructure</code>, <code>RemoveRowByIndexStructure</code>, <code>RemoveTrailingColumnStructure</code>, <code>ReplaceEntriesStructure</code>, <code>SplitCellStructure</code>, <code>TransposeMatrixStructure</code>.
     * @return {(module:model/AddHeaderNameStructure|module:model/FillEmptyColumnStructure|module:model/FillEmptyRowStructure|module:model/MergeColumnsStructure|module:model/PivotMatrixStructure|module:model/RemoveColumnByIndexStructure|module:model/RemoveFooterStructure|module:model/RemoveGroupedHeaderStructure|module:model/RemoveHeaderStructure|module:model/RemoveInvalidRowsStructure|module:model/RemoveKeywordsStructure|module:model/RemoveLeadingColumnStructure|module:model/RemoveRowByIndexStructure|module:model/RemoveTrailingColumnStructure|module:model/ReplaceEntriesStructure|module:model/SplitCellStructure|module:model/TransposeMatrixStructure)} The actual instance.
     */
    getActualInstance() {
        return this.actualInstance;
    }

    /**
     * Sets the actual instance, which can be <code>AddHeaderNameStructure</code>, <code>FillEmptyColumnStructure</code>, <code>FillEmptyRowStructure</code>, <code>MergeColumnsStructure</code>, <code>PivotMatrixStructure</code>, <code>RemoveColumnByIndexStructure</code>, <code>RemoveFooterStructure</code>, <code>RemoveGroupedHeaderStructure</code>, <code>RemoveHeaderStructure</code>, <code>RemoveInvalidRowsStructure</code>, <code>RemoveKeywordsStructure</code>, <code>RemoveLeadingColumnStructure</code>, <code>RemoveRowByIndexStructure</code>, <code>RemoveTrailingColumnStructure</code>, <code>ReplaceEntriesStructure</code>, <code>SplitCellStructure</code>, <code>TransposeMatrixStructure</code>.
     * @param {(module:model/AddHeaderNameStructure|module:model/FillEmptyColumnStructure|module:model/FillEmptyRowStructure|module:model/MergeColumnsStructure|module:model/PivotMatrixStructure|module:model/RemoveColumnByIndexStructure|module:model/RemoveFooterStructure|module:model/RemoveGroupedHeaderStructure|module:model/RemoveHeaderStructure|module:model/RemoveInvalidRowsStructure|module:model/RemoveKeywordsStructure|module:model/RemoveLeadingColumnStructure|module:model/RemoveRowByIndexStructure|module:model/RemoveTrailingColumnStructure|module:model/ReplaceEntriesStructure|module:model/SplitCellStructure|module:model/TransposeMatrixStructure)} obj The actual instance.
     */
    setActualInstance(obj) {
       this.actualInstance = Structure.constructFromObject(obj).getActualInstance();
    }

    /**
     * Returns the JSON representation of the actual instance.
     * @return {string}
     */
    toJSON = function(){
        return this.getActualInstance();
    }

    /**
     * Create an instance of Structure from a JSON string.
     * @param {string} json_string JSON string.
     * @return {module:model/Structure} An instance of Structure.
     */
    static fromJSON = function(json_string){
        return Structure.constructFromObject(JSON.parse(json_string));
    }
}

/**
 * @member {module:model/ConverterType} converterType
 */
Structure.prototype['converterType'] = undefined;

/**
 * A name for the structure. This can be used to identify the structure in the UI. It can be any string. 
 * @member {String} name
 */
Structure.prototype['name'] = undefined;

/**
 * A description for the structure. This can be used to provide more information about the structure in the UI. It can be any string. 
 * @member {String} description
 */
Structure.prototype['description'] = undefined;

/**
 * The indices of the rows to fill
 * @member {Array.<Number>} rowIndex
 */
Structure.prototype['rowIndex'] = undefined;

/**
 * The indices of the columns to merge
 * @member {Array.<Number>} columnIndex
 */
Structure.prototype['columnIndex'] = undefined;

/**
 * The start row index of the area to split (inclusive).
 * @member {Number} startRow
 */
Structure.prototype['startRow'] = undefined;

/**
 * The index of the first data column to the right of the grouped header.
 * @member {Number} startColumn
 */
Structure.prototype['startColumn'] = undefined;

/**
 * The header names
 * @member {Array.<String>} headerNames
 */
Structure.prototype['headerNames'] = undefined;

/**
 * @member {module:model/HeaderPlacementType} headerPlacementType
 */
Structure.prototype['headerPlacementType'] = undefined;

/**
 * The maximum number of invalid values in a row to be considered invalid.
 * @member {Number} threshold
 */
Structure.prototype['threshold'] = undefined;

/**
 * The list of values to be considered invalid.
 * @member {Array.<String>} blockList
 */
Structure.prototype['blockList'] = undefined;

/**
 * The string to search for in the table.
 * @member {String} search
 */
Structure.prototype['search'] = undefined;

/**
 * The regex pattern to search for in the table.
 * @member {String} regexSearch
 */
Structure.prototype['regexSearch'] = undefined;

/**
 * The value to replace the found entries with.
 * @member {String} replacement
 */
Structure.prototype['replacement'] = undefined;

/**
 * The end row index of the area to split (exclusive).
 * @member {Number} endRow
 */
Structure.prototype['endRow'] = undefined;

/**
 * The delimiter to split the entries by. Line break by default. 
 * @member {String} delimiter
 */
Structure.prototype['delimiter'] = undefined;

/**
 * The mode to split the entries. Can be either 'row' or 'column'. 'row' will split the entries into multiple rows. 'column' will split the entries into multiple columns. 
 * @member {module:model/Structure.ModeEnum} mode
 */
Structure.prototype['mode'] = undefined;

/**
 * The name of the new column
 * @member {String} headerName
 */
Structure.prototype['headerName'] = undefined;

/**
 * The order in which the cells will be checked for non-empty values
 * @member {Array.<Number>} precedenceOrder
 */
Structure.prototype['precedenceOrder'] = undefined;

/**
 * @member {Object.<String, Array.<Number>>} pivotField
 */
Structure.prototype['pivotField'] = undefined;

/**
 * Indices that define the start of new data blocks
 * @member {Array.<Number>} blockIndices
 */
Structure.prototype['blockIndices'] = undefined;

/**
 * Column names whose values should be carried forward if empty
 * @member {Array.<String>} keysToCarryForward
 */
Structure.prototype['keysToCarryForward'] = undefined;

/**
 * A list of keywords to match against.  If a cell contains any of these keywords, the corresponding row or column will be removed. 
 * @member {Array.<String>} keywords
 */
Structure.prototype['keywords'] = undefined;

/**
 * Whether to remove rows that contain a matching keyword.
 * @member {Boolean} removeRows
 * @default true
 */
Structure.prototype['removeRows'] = true;

/**
 * Whether to remove columns that contain a matching keyword.
 * @member {Boolean} removeColumns
 * @default true
 */
Structure.prototype['removeColumns'] = true;

/**
 * @member {Boolean} ignoreCase
 * @default true
 */
Structure.prototype['ignoreCase'] = true;

/**
 * @member {module:model/MatchType} matchType
 */
Structure.prototype['matchType'] = undefined;


Structure.OneOf = ["AddHeaderNameStructure", "FillEmptyColumnStructure", "FillEmptyRowStructure", "MergeColumnsStructure", "PivotMatrixStructure", "RemoveColumnByIndexStructure", "RemoveFooterStructure", "RemoveGroupedHeaderStructure", "RemoveHeaderStructure", "RemoveInvalidRowsStructure", "RemoveKeywordsStructure", "RemoveLeadingColumnStructure", "RemoveRowByIndexStructure", "RemoveTrailingColumnStructure", "ReplaceEntriesStructure", "SplitCellStructure", "TransposeMatrixStructure"];

export default Structure;

