/**
 * TH1
 * TH1
 *
 * The version of the OpenAPI document: 1.28.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ConverterType from './ConverterType';

/**
 * The StructureSummary model module.
 * @module model/StructureSummary
 * @version 1.28.0
 */
class StructureSummary {
    /**
     * Constructs a new <code>StructureSummary</code>.
     * This is a summary of a structure. It only contains the converterType to identify the use of the structure. 
     * @alias module:model/StructureSummary
     * @param converterType {module:model/ConverterType} 
     */
    constructor(converterType) { 
        
        StructureSummary.initialize(this, converterType);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, converterType) { 
        obj['converterType'] = converterType;
    }

    /**
     * Constructs a <code>StructureSummary</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/StructureSummary} obj Optional instance to populate.
     * @return {module:model/StructureSummary} The populated <code>StructureSummary</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new StructureSummary();

            if (data.hasOwnProperty('converterType')) {
                obj['converterType'] = ConverterType.constructFromObject(data['converterType']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>StructureSummary</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>StructureSummary</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of StructureSummary.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }

        return true;
    }


}

StructureSummary.RequiredProperties = ["converterType"];

/**
 * @member {module:model/ConverterType} converterType
 */
StructureSummary.prototype['converterType'] = undefined;






export default StructureSummary;

