/**
 * TH1
 * TH1
 *
 * The version of the OpenAPI document: 1.28.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ReportType from './ReportType';

/**
 * The TransposeMatrixReport model module.
 * @module model/TransposeMatrixReport
 * @version 1.28.0
 */
class TransposeMatrixReport {
    /**
     * Constructs a new <code>TransposeMatrixReport</code>.
     * Report indicating whether a matrix is detected as transposed
     * @alias module:model/TransposeMatrixReport
     * @param reportType {module:model/ReportType} 
     * @param detected {Boolean} True if the matrix is detected as transposed, false otherwise
     */
    constructor(reportType, detected) { 
        
        TransposeMatrixReport.initialize(this, reportType, detected);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, reportType, detected) { 
        obj['reportType'] = reportType;
        obj['detected'] = detected;
    }

    /**
     * Constructs a <code>TransposeMatrixReport</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TransposeMatrixReport} obj Optional instance to populate.
     * @return {module:model/TransposeMatrixReport} The populated <code>TransposeMatrixReport</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TransposeMatrixReport();

            if (data.hasOwnProperty('reportType')) {
                obj['reportType'] = ReportType.constructFromObject(data['reportType']);
            }
            if (data.hasOwnProperty('detected')) {
                obj['detected'] = ApiClient.convertToType(data['detected'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>TransposeMatrixReport</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>TransposeMatrixReport</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of TransposeMatrixReport.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }

        return true;
    }


}

TransposeMatrixReport.RequiredProperties = ["reportType", "detected"];

/**
 * @member {module:model/ReportType} reportType
 */
TransposeMatrixReport.prototype['reportType'] = undefined;

/**
 * True if the matrix is detected as transposed, false otherwise
 * @member {Boolean} detected
 */
TransposeMatrixReport.prototype['detected'] = undefined;






export default TransposeMatrixReport;

