name: Frontend NPM Install

on:
  push:
  pull_request:

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: NPM Install
        run: |
          cd frontend/js-client
          npm install
          npm pack
          cd ..
          npm install
